"""Deterministic multi-backend expansion; returning bytes has no filesystem effects."""
import json
from verification.dsl import Expr, emit, node, require


def mutations(expr):
    """Every single-operator change; no assumption that a mutation is observable."""
    replacements = {"and": "or", "or": "and", "eq": "ne", "ne": "eq", "lt": "le", "le": "lt", "band": "bor", "bor": "band"}
    if expr.op in replacements:
        yield node(replacements[expr.op], *expr.args)
    if expr.op in {"and", "or"}:
        # Deleting one requirement can expose an under-specified clause even
        # when wholesale inversion or replacing AND with OR already fails.
        yield from expr.args
    if expr.op == "not":
        yield expr.args[0]
    if expr.op not in {"var", "literal"}:
        for index, child in enumerate(expr.args):
            for changed in mutations(child):
                yield node(expr.op, *expr.args[:index], changed, *expr.args[index + 1:])


def instances(registry, mutants=False):
    cases = []
    for c in registry.contracts.values():
        c.validate()
        if not mutants:
            cases.append((c.name, c, c.body))
            continue
        seen = set()
        for body in __import__("itertools").chain([~c.body], mutations(c.body)):
            identity = emit(body)
            if identity in seen: continue
            seen.add(identity)
            cases.append((f"{c.name}_m{len(seen):02}", c, body))
            require(len(cases) <= 256, "mutation expansion exceeds 256 cases; split the contract set")
    return cases


def expand(registry, *, mutants=False):
    contracts = list(registry.contracts.values())
    require(0 < len(contracts) <= 64, "expected 1..64 named contracts")
    rust, verus, harnesses, witnesses = [], [], [], []
    for name, c, expression in instances(registry, mutants):
        args = ", ".join(f"{n}: {t}" for n, t in c.parameters)
        body = emit(expression)
        # Byte-identical executable expressions in both Rust and Verus.
        rust.append(f"pub fn {name}({args}) -> bool {{ {body} }}")
        clauses = ",\n        ".join(emit(p) for p in c.properties)
        verus.append(f"pub fn {name}({args}) -> (result: bool)\n    ensures {clauses}\n{{ {body} }}")
        setup = "\n".join(f"        let {n}: {t} = kani::any();" for n, t in c.parameters)
        call = f"{name}({', '.join(n for n, _ in c.parameters)})"
        checks = "\n".join(f"        assert!({emit(p)});" for p in c.properties)
        harnesses.append(f"    #[kani::proof]\n    fn law_{name}() {{\n{setup}\n        let result = {call};\n{checks}\n    }}")
        for i, (inputs, expected) in enumerate(() if mutants else c.witnesses):
            values = ", ".join(str(v).lower() if t == "bool" else f"{v}{t}" for (_, t), v in zip(c.parameters, inputs))
            witnesses.append(f"    #[test]\n    fn {c.name}_{i}() {{ assert_eq!({c.name}({values}), {str(expected).lower()}); }}")
    banner = "// Generated by tools/meta.py; edit verification/specification.py.\n"
    lib = banner + "#![forbid(unsafe_code)]\n#![allow(unused_parens)]\n" + "\n".join(rust)
    lib += "\n#[cfg(kani)]\nmod proofs {\n    use super::*;\n" + "\n".join(harnesses) + "\n}\n"
    lib += "\n#[cfg(test)]\nmod witnesses {\n    use super::*;\n" + "\n".join(witnesses) + "\n}\n"
    manifest = '''[package]
name = "ncp-metaverify"
version = "0.1.0"
edition = "2024"
publish = false
license = "RPL-1.5"
[workspace]
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
'''
    return {
        "kernel/Cargo.toml": manifest,
        "kernel/Cargo.lock": '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "ncp-metaverify"\nversion = "0.1.0"\n',
        "kernel/src/lib.rs": lib,
        "verus.rs": banner + "use vstd::prelude::*;\nverus! {\n" + "\n\n".join(verus) + "\n}\nfn main() {}\n",
        "scope.json": json.dumps({c.name: {"scope": c.scope, "parameters": dict(c.parameters),
                                          "postconditions": len(c.properties)} for c in contracts}, indent=2) + "\n",
    }
