"""Deterministic multi-backend expansion; returning bytes has no filesystem effects."""
import json
from verification.dsl import emit, require


def expand(registry, *, mutants=False):
    contracts = list(registry.contracts.values())
    require(0 < len(contracts) <= 64, "expected 1..64 named contracts")
    rust, verus, harnesses, witnesses = [], [], [], []
    for c in contracts:
        c.validate()
        args = ", ".join(f"{n}: {t}" for n, t in c.parameters)
        body = emit(~c.body if mutants else c.body)
        # Byte-identical executable expressions in both Rust and Verus.
        rust.append(f"pub fn {c.name}({args}) -> bool {{ {body} }}")
        clauses = ",\n        ".join(emit(p) for p in c.properties)
        verus.append(f"pub fn {c.name}({args}) -> (result: bool)\n    ensures {clauses}\n{{ {body} }}")
        setup = "\n".join(f"        let {n}: {t} = kani::any();" for n, t in c.parameters)
        call = f"{c.name}({', '.join(n for n, _ in c.parameters)})"
        checks = "\n".join(f"        assert!({emit(p)});" for p in c.properties)
        harnesses.append(f"    #[kani::proof]\n    fn law_{c.name}() {{\n{setup}\n        let result = {call};\n{checks}\n    }}")
        for i, (inputs, expected) in enumerate(c.witnesses):
            values = ", ".join(str(v).lower() if t == "bool" else f"{v}{t}" for (_, t), v in zip(c.parameters, inputs))
            witnesses.append(f"    #[test]\n    fn {c.name}_{i}() {{ assert_eq!({c.name}({values}), {str(expected).lower()}); }}")
    banner = "// Generated by tools/meta.py; edit verification/specification.py.\n"
    lib = banner + "#![forbid(unsafe_code)]\n#![allow(unused_parens)]\n" + "\n".join(rust)
    lib += "\n#[cfg(kani)]\nmod proofs {\n    use super::*;\n" + "\n".join(harnesses) + "\n}\n"
    lib += "\n#[cfg(test)]\nmod witnesses {\n    use super::*;\n" + "\n".join(witnesses) + "\n}\n"
    manifest = '''[package]
name = "ncp-metaverify"
version = "0.1.0"
edition = "2024"
publish = false
license = "RPL-1.5"
[workspace]
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
'''
    return {
        "kernel/Cargo.toml": manifest,
        "kernel/Cargo.lock": '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "ncp-metaverify"\nversion = "0.1.0"\n',
        "kernel/src/lib.rs": lib,
        "verus.rs": banner + "use vstd::prelude::*;\nverus! {\n" + "\n\n".join(verus) + "\n}\nfn main() {}\n",
        "scope.json": json.dumps({c.name: {"scope": c.scope, "parameters": dict(c.parameters),
                                          "postconditions": len(c.properties)} for c in contracts}, indent=2) + "\n",
    }
