---
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: frr.frr.frr
ansible_user: ansible
ansible_network_cli_ssh_type: libssh
ansible_host_key_checking: true
ansible_libssh_host_key_checking: true
ansible_libssh_config_file: "{{ ex457_ssh_config.path }}"
