---
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9:latest
dependencies:
  galaxy: ../requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf
additional_build_files:
  - src: ../tools/patch_libssh.py
    dest: patches
additional_build_steps:
  append_galaxy:
    - COPY _build/patches/patch_libssh.py /tmp/patch_libssh.py
    - RUN $PYCMD /tmp/patch_libssh.py /usr/share/ansible/collections
