name: NVIDIA Reference

on:
  workflow_dispatch:

jobs:
  superpod-b300-xdr:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    env:
      NVIDIA_SUPERPOD_PDF: >-
        https://docs.nvidia.com/dgx-superpod/reference-architecture/scalable-infrastructure-b300-xdr/latest/_downloads/f2d6423ee942e3f144511f5df58e3080/RA11339001-DSPB300-XDR-ReferenceArch.pdf

    steps:
      - name: Download PDF
        shell: bash
        run: |
          curl \
            --fail \
            --silent \
            --show-error \
            --location \
            "$NVIDIA_SUPERPOD_PDF" \
            --output /tmp/nvidia-superpod-reference.pdf

      - name: Upload PDF as workflow artifact
        uses: actions/upload-artifact@v7
        with:
          path: /tmp/nvidia-superpod-reference.pdf
          archive: false
          if-no-files-found: error
